{% set name = "venvstacks" %}
{% set version = "0.3.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/venvstacks-{{ version }}.tar.gz
  sha256: 836971ae638b29f896ebaeef797edc2e8a4d1b6b815379bfe37a532ba5aac938

build:
  entry_points:
    - venvstacks = venvstacks.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - pip >=24.1.1
    - pdm >=2.17.3
    - python-uv >=0.2.33
    - typer-slim >=0.12.4

test:
  imports:
    - venvstacks
  commands:
    - pip check
    - venvstacks --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lmstudio-ai/venvstacks
  doc_url: https://venvstacks.lmstudio.ai/
  summary: Use layered Python virtual environment stacks to share large dependencies.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
