schema_version: 1

context:
  name: venvstacks
  version: "0.6.0"
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/venvstacks-${{ version }}.tar.gz
  sha256: 11d9da7c40fb01fdfe43b097bf3b30c67637a2c2aeb48f73c35ab8392f0fea37

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - venvstacks = venvstacks.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }}
    - pip >=24.1.1
    - pdm >=2.17.3
    - python-uv >=0.2.33
    - typer >=0.12.4
    - tomlkit >=0.13.2

tests:
  - python:
      imports:
        - venvstacks
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - venvstacks --help

about:
  summary: Use layered Python virtual environment stacks to share large dependencies.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/lmstudio-ai/venvstacks
  documentation: https://venvstacks.lmstudio.ai/

extra:
  recipe-maintainers:
    - thewchan
